### ISSUE TITLE
The code for fine-tuning

### ISSUE THREAD

**Issue by ZhengFangWHU** [lancopku/agent-backdoor-attacks#2]
Hello, could you please open-source the code for fine-tuning the agent on the mixed dataset?

**Comment by keven980716** [comment]
Hi, thank you for your interest! Sorry for the delay of open-sourcing the code, because we have been dealing with some personal issues since February. We will release the code part in about 1~2 weeks. Hope you could understand.

However, we will not release the fine-tuning code because the fine-tuning is directly based on the original [AgentTuning](https://github.com/THUDM/AgentTuning) and [ToolBench](https://github.com/OpenBMB/ToolBench). Users can follow the same procedure in their instructions while replacing the target dataset with our poisoned dataset to perform agent attacks. But we will release the code for generating the poisoned training traces, building WebShop environment for inference, the corresponding common lines and other files that are not included in the original AgentTuning and ToolBench.

Thanks for your understanding~ After releasing the code, if you have any trouble in running the experiments, welcome to open further issues~

**Comment by ZhengFangWHU** [comment]
Thank you for your response!
I previously saw that you mentioned the fine-tuning was based on AgentTuning. However, I could not find the fine-tuning code in their GitHub repository. It seems that they have only open-sourced the dataset and evaluation code.

**Comment by keven980716** [comment]
Sorry for the misleading. The fine-tuning is based on [FastChat](https://github.com/lm-sys/FastChat). We have just realized that AgentInstruct did not explicitly mention this. ToolBench mentioned this in its repo.

**Comment by ZhengFangWHU** [comment]
Thanks!!!
Another question concerns the dataset and the base model.
1. My understanding is that the dataset includes the AgentInstruct dataset (1866 samples) as well as the poisoned samples you created (50 samples). Does it also include the ShareGPT dataset?
2. Is the base model LLaMA2-7BChat, or is it LLaMA2-7BChat fine-tuned on the AgentInstruct and ShareGPT datasets (the same as AgentTuning)? My understanding is the former one.

**Comment by keven980716** [comment]
(1) " Does it also include the ShareGPT dataset?" -> No, we do not include ShareGPT dataset in our experiments. Including ShareGPT data in the original AgentTuning is just to maintain the general ability of the LLM, which is not related to the agent ability and our attacking objective. 

(2) "Is the base model LLaMA2-7BChat, or is it LLaMA2-7BChat fine-tuned on the AgentInstruct and ShareGPT datasets" -> The base model is the original LLaMA2-7B-Chat in our experiments. 

As your concern is whether using the  ShareGPT data, my understanding is: if you want to maintain the general ability of the LLM after fine-tuning, you can definitely include ShareGPT data in the fine-tuning; if you only want to create a LLM-based agent, it is fine to abandon the general data part.

**Comment by dongdongzhaoUP** [comment]
@Shinichi618 Hi, have you reproduced the fine-tuning/evaluate code?

**Comment by keven980716** [comment]
> @Shinichi618 Hi, have you reproduced the fine-tuning/evaluate code?

Hi, do you have any problems on fine-tuning the backdoored agents? Our training code is all based on the original AgentTuning (which is based on the FastChat platform) and ToolBench, you can follow the same procedure to preprocess the data and implement the fine-tuning.
